### PR TITLE
Tarball & git support support

### LINKED ISSUE #24: Tarball support missing
#### Issue description:

Currently output from `synp` is different to what `npm i` would generate in the `package-lock.json`.

I made a small repo to demonstrate the scenario (follow the readme): https://github.com/DeTeam/synp-tarball (contains `yarn.lock` and `package.json`)

### PR DESCRIPTION
**Pull request by DeTeam**
Fixes #24
Related to #27

- [x] Failing tests for tarball support
- [x] Failing tests for git dependencies
- [x] Fix for both of tarball & git

### CODE REVIEW

**Comment by DeTeam** [comment]
@imsnif I need your advice:

`npmEntry` currently gets real info from actual `node_modules` and `yarn.lock`, it doesn't get info from the main `package.json`, this means that we have to inspect what's in `nodeModulesTree[mPath]` in order to get some useful information.

Which information is needed? We need to know if user request git/tarball (right now we can only know that it's resolved to such).

One option would be to go for `nodeModulesTree[mPath]._requested.raw` (or some other field from`_requested`) or also pass info from `package.json` to that function.

First option worries me a bit, second one seem better, though also bigger (fine going for it).

What do you think?

**Comment by imsnif** [comment]
Hey @DeTeam - without looking deeply into it (I have some time constraints in the next few days, my apologies): the `nmtree` module uses `package.json` - won't the module requiring the github dependency have what we need? (if this doesn't help, I promise to take a deeper look asap)

**Comment by DeTeam** [comment]
@imsnif just realized that I submitted `tests/fixtures/<NEW FIXTURES>/node_modules/abab/package.json` generated using `npm i` (I used it to get a snapshot of `package-lock.json`), if I just run `yarn` there, I don't get this info, however now (yarn v1.10.1) I also get `.yarn-integrity` in node_modules...)

Getting confused with which approach to pick here 🤔 

What I know for sure, is that we need to operate on `npmEntry` function here.

**Comment by imsnif** [comment]
Right, now I got a chance to actually take a look at the code and I understand your question. :)

I think getting the information from the `_requested.raw` field is a good approach (we can destructure it at the same place we get the name, version and dependencies). I'd say a safe bet would be to check if `_requested` exists and its `type` field is git, and there insert the new functionality. Otherwise, we can always fall back on what happens now.
If it works well, we might even combine it with the git `codeload` urls to be more elegant (that file has seen some work and I'm ashamed to say not a lot of refactoring :) ).

The `yarn-integrity` is not the same thing as the `integrity` in the lockfile, don't worry about it. :) The integrity fields in the lockfile are quite a late edition and were added in order to support `sha512` authentication.

I hope everything is clearer now? Can I help with anything else? Please do not hesitate to ask.

**Comment by DeTeam** [comment]
Hey @imsnif 

Added two more commits:

- modify fixture such that it doesn't contains npm-specific meta data (cause we operate in the context where only `yarn` is run)
- add support for git and tarball (respecting format generated by `npm@6.2.0`)

What's missing now for tests to pass is the integrity: we generate sha-1 whilst npm package lock contains sha-512. Do you have any suggestions on that one?

**Comment by DeTeam** [comment]
A, as I can see in https://github.com/yarnpkg/yarn/issues/816 and https://github.com/yarnpkg/yarn/pull/5042 sha512-integrity has landed  in yarn :) Nice done!

However it would probably not be there for neither git (which is ok?) nor tarballs (bummer!) via yarn. Should we take a different route there?

**Comment by imsnif** [comment]
Hey @DeTeam - great work so far!

Since this is a conversion tool, what I'd do in this case is produce `sha1` when the entry has `sha1` and `sha512` when it has `sha512`. I feel that doing more is overkill, wdyt?
If you agree, to make the tests pass feel free to just change the fixture. As long as a fixture is installable with the other tool without locked versions changing, I think we're good. There's only so much we can do for interoperability. :)

**Comment by DeTeam** [comment]
@imsnif sounds good, I'll adjust the fixtures then.
Will also check our real projects which was supposed to benefit from this fix.

**Comment by DeTeam** [comment]
@imsnif pushed some changes. Is that what you meant?

\* current implementation for tarball support seem to be fine for our internal use-case, btw

**Pull request merged**
