### PR TITLE
chore: update lockfile, tweak up travis config

### PR DESCRIPTION
**Pull request by antongolub**

### CODE REVIEW

**Comment by antongolub** [comment]
Hey, @imsnif,

travis-ci.org [is going to be frozen](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-what-will-happen-to-travis-ciorg-after-december-31st-2020) very soon. Could you transfer **synp** repo to travis-ci.com? This action is permissible for github org/scope owners only.

**Comment by imsnif** [comment]
Done :) (I think? let me know if I did it wrong or missed something)

**Comment by antongolub** [comment]
Everything seems fine. Thanks.

**Pull request merged**
