### PR TITLE
Cannot read property 'replace' of undefined

### PR DESCRIPTION
**Pull request by styx**
When dependency is installed form git there is now `integrity` in `package-lock.json`

### CODE REVIEW

**Comment by imsnif** [comment]
Hey @styx - want to tell me a little more about the use-case and issue this addresses?

**Comment by tech4him1** [comment]
@imsnif I believe this is intended as a fix for #12.

**Comment by imsnif** [comment]
@tech4him1 - yeah, but it's hard to know the "poet's intent" without a unit test... I'd be happy to merge this if a test is added that clarifies the use-case.

**Comment by tech4him1** [comment]
👍 completely agree

**Comment by styx** [comment]
@imsnif sure I'll add a test case then. Sorry for late response.

**Comment by imsnif** [comment]
Hey @styx - thanks for this, the test looks great! However, when I try to install the converted yarn.lock file, it fails:
```
$ yarn
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "Invalid protocol: github:"
```

If I'm not mistaken, `yarn.lock` needs the full remote url. I think this can be an easy fix with a regex. Want to give it a go?

**Comment by styx** [comment]
@imsnif yeah, that's another issue. I just changed url and forgot about it. BTW the repo used in test is private. I think I should change that to something open source and will add conversion for protocol too.

There is some options here like: `ssh+git`, just `git`. I'm using `git://` as I got some issues with ssh and haven't time to investigate why it doesn't see my private key. Also `https://` is another option but it is ok only for public repos. What do you think?

**Comment by imsnif** [comment]
@styx - let's go with `https://` - I think that's the most common case. I don't think there should be an effect on private repos, though maybe I'm missing something ofc. 

If you'd like to look into it and add another test case if there are specific concerns (maybe mocking the private repo somehow?) - that would be awesome!

But even if not, public repo support would still be great.

As for the test - it worked for me locally and is running alright on Travis... so is the repo temporarily public, or...?

**Comment by styx** [comment]
@imsnif oh, yes, it is public, just forked to our company account.

Cool, `https://` sounds reasonable, will add conversion for it.

**Comment by styx** [comment]
@imsnif heh, A long time ago in a galaxy far, far away I started working on this one (: 
At last I added this simple change.

**Comment by styx** [comment]
Is anything more required from my side?

**Comment by imsnif** [comment]
No @styx - my apologies! I will get to this next week (sorry, busy times!)

**Comment by styx** [comment]
@imsnif yeah, no worries and thanks

**Comment by imsnif** [comment]
@styx - merged and published as `1.3.0`. My apologies for the delay in reviewing this. Thanks for your contribution!

**Pull request merged**
