### PR TITLE
Provide continuous delivery pipeline

### PR DESCRIPTION
**Pull request by antongolub**
* Provide continuous delivery via [semantic-release](https://github.com/semantic-release/semantic-release)
* Up deps

@imsnif, 

I need your help. Could you generate **npm** and **github** tokens with read/write permissions for publishing? These tokens should be added to Travis config. Here's the example.
travis-config-example

### CODE REVIEW

**Comment by imsnif** [comment]
Hey @antongolub - sorry it took me a short while to get to this. I added you as a maintainer on npm as well, so I think you can now add your tokens it will be enough, right?

**Comment by antongolub** [comment]
@imsnif

I could issue a github token, ok, I'll do it. But I have no npm permissions.

**Comment by imsnif** [comment]
That's odd... can you maybe check again? I just added you, maybe it takes some time to update?

**Comment by antongolub** [comment]
@imsnif

logout+login does all the magic. Now everything seems to be ok. Thanks.

**Pull request merged**
