### PR TITLE
chore: up deps

### PR DESCRIPTION
**Pull request by antongolub**
* Adapt CLI layer to Commander v7
* Meet the requirements of Standardjs v16
* Up deps
* Migrate to GH actions

### CODE REVIEW

**Comment by antongolub** [comment]
@imsnif, 
Hey, Aram. It seems that Travis-ci is no longer ready to give free quota for every OSS project (my request of 29th Dec was left without a meaningful answer). Therefore, I propose to move to GH actions. As a project owner, only you can define secrets:
```yaml
- name: Semantic Release
  uses: cycjimmy/semantic-release-action@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by antongolub** [comment]
@imsnif,

Could you take a look?

**Comment by imsnif** [comment]
Sorry, I'm afraid I'm not finding the time to get deeper into this. What do I need to do exactly?

**Comment by antongolub** [comment]
image

**Comment by imsnif** [comment]
Didn't you want to move to github actions though?

**Comment by antongolub** [comment]
Exactly! This PR brings GH Actions. Unfortunately, I have no permissions to assign the required secrets.

**Comment by imsnif** [comment]
> Exactly! This PR brings GH Actions. Unfortunately, I have no permissions to assign the required secrets.

I would be happy to help, but I unfortunately don't have a lot of time these days. If you can tell me exactly what I need to do, I would be happy to do it.

**Comment by antongolub** [comment]
@imsnif, 

Sure.
1) Open 'imsnif/synp' repo settings.
image

2) Open `Secrets` in the left pane.
image

3) Set a pair of variables:
* `GH_TOKEN` — github token with read/write grants
* `NPM_TOKEN` — npm token with push permissions

**Comment by imsnif** [comment]
Done :) Anything else?

**Comment by antongolub** [comment]
@imsnif,

Everything seems fine. Thanks. 
https://github.com/imsnif/synp/runs/1887883602?check_suite_focus=true

**Pull request merged**
